### ISSUE TITLE
Code Not Running

### ISSUE THREAD

**Issue by SkimmerLive** [krthush/2d-unity-movement#1]
Namespace name "Passenger" couldn't be found. I went in to Project settings and copied the settings under Passenger mover not working. Still won't run, help!

**Comment by krthush** [comment]
hey i just downloaded the project and tried it out, seems to be working on my end - can you provide more details? perhaps what version of unity you are using?

![image](https://user-images.githubusercontent.com/33790334/129262054-8b9d3d82-a7ec-494e-804f-90611b0e4ada.png)

the version above is what I've tested it on

**Comment by SkimmerLive** [comment]
I didn't download the protect just copied the assets so that may be the issue, thanks!

**Comment by krthush** [comment]
yeah you have to be careful with the way you work with unity, it needs to build correctly - closing the issue for now!
